services:
  backend:
    image: flask-sysacad:v1.0.0
    deploy:
      replicas: 3
    networks:
      - mired
    #ports:
    # - 5000:5000
    environment:
      - FLASK_CONTEXT=${FLASK_CONTEXT}
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
      - SQLALCHEMY_RECORD_QUERIES=${SQLALCHEMY_RECORD_QUERIES}
      - PROD_DATABASE_URI=${PROD_DATABASE_URI}
      - HASHIDS_MIN_LENGTH=${HASHIDS_MIN_LENGTH}
      - HASHIDS_ALPHABET=${HASHIDS_ALPHABET}
      - HASHIDS_SALT=${HASHIDS_SALT}
      - SECRET_KEY=${SECRET_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.universidad.localhost`)"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
      - "traefik.docker.network=mired"
networks:
  mired:
    external: true
