from .universidad import Universidad
from .facultad import Facultad
from .especialidad import Especialidad
from .plan import Plan
from .materia import Materia
from .tipoEspecialidad import TipoEspecialidad
from .orientacion import Orientacion
from .cargo import Cargo
from .area import Area
from .grupo import Grupo