from .universidad import Universidad
from .facultad import Facultad
from .especialidad import Especialidad
from .plan import Plan
from .materia import Materia
from .orientacion import Orientacion
from .alumno import Alumno
from .tipoEspecialidad import TipoEspecialidad
from .orientacion import Orientacion
from .grado import Grado
from .departamento import Departamento
from .cargo import Cargo
from .area import Area
from .grupo import Grupo
from .tipodocumento import TipoDocumento
