from .autoridad_respositorio import AutoridadRepository
from .facultad_repository import FacultadRepository
from .plan_repository import PlanRepository
from .cargo_repository import CargoRepository
from .categoria_cargo_repository import CategoriaCargoRepository